# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20170730_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'parent_task__id', 'position']},
        ),
        migrations.RemoveField(
            model_name='task',
            name='context_tag',
        ),
        migrations.AddField(
            model_name='task',
            name='context_tags',
            field=models.ManyToManyField(blank=True, null=True, to='tasks.ContextTag'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High Priority'), ('M', 'Medium Priority'), ('L', 'Low Priority')], default='M', help_text='Enter a priority level', max_length=1),
        ),
    ]
